// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUnu5FgAHJxLgc4NmlVFAv7D3FrsgblFQ',
    appId: '1:461172553381:web:2e5119d999ff82c7ca3f4c',
    messagingSenderId: '461172553381',
    projectId: 'soul-mbti-40aca',
    authDomain: 'soul-mbti-40aca.firebaseapp.com',
    storageBucket: 'soul-mbti-40aca.appspot.com',
    measurementId: 'G-3KYC3DBX3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGrM7LszWwRFHoMfmFIrdrDSgCXMRSRhA',
    appId: '1:461172553381:android:57a2827abeaeef86ca3f4c',
    messagingSenderId: '461172553381',
    projectId: 'soul-mbti-40aca',
    storageBucket: 'soul-mbti-40aca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2gILgSHoShTTLEjMqZxvz47_kTZtGnE',
    appId: '1:461172553381:ios:b76e4019432c530dca3f4c',
    messagingSenderId: '461172553381',
    projectId: 'soul-mbti-40aca',
    storageBucket: 'soul-mbti-40aca.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2gILgSHoShTTLEjMqZxvz47_kTZtGnE',
    appId: '1:461172553381:ios:b76e4019432c530dca3f4c',
    messagingSenderId: '461172553381',
    projectId: 'soul-mbti-40aca',
    storageBucket: 'soul-mbti-40aca.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUnu5FgAHJxLgc4NmlVFAv7D3FrsgblFQ',
    appId: '1:461172553381:web:54acee62686a86b9ca3f4c',
    messagingSenderId: '461172553381',
    projectId: 'soul-mbti-40aca',
    authDomain: 'soul-mbti-40aca.firebaseapp.com',
    storageBucket: 'soul-mbti-40aca.appspot.com',
    measurementId: 'G-0G5HJY3ES7',
  );
}
